/** Design 1 stack pack — Chroma + Loki + Prometheus + Langfuse */
window.ARCH_DESIGN_PACKS = window.ARCH_DESIGN_PACKS || {};
window.ARCH_DESIGN_LOGOS = Object.assign(window.ARCH_DESIGN_LOGOS || {}, {
  grafana: { label: 'Grafana', src: '/static/designs/d1/logos/grafana.svg?v=1' },
  prometheus: { label: 'Prometheus', src: '/static/designs/d1/logos/prometheus.svg?v=1' },
  langfuse: { label: 'Langfuse', src: '/static/designs/d1/logos/langfuse.svg?v=1' },
  chroma: { label: 'Chroma', src: '/static/designs/d1/logos/chroma.svg?v=1' },
});

window.ARCH_DESIGN_PACKS.d1 = {
  id: 'd1',
  n: 1,
  name: 'Design 1',
  tagline: 'Lightweight dev-prod path',
  stack: 'Chroma + Loki + Prometheus + Langfuse',
  deploy: './deploy.sh up',
  pick: 'Ship the capstone on a laptop today.',
  vector: 'ChromaDB',
  vectorUrl: '/static/tools/chroma.html',
  logs: 'Loki + Promtail',
  metrics: 'Prometheus',
  dashboards: 'Grafana',
  llmops: 'Langfuse',
  evals: 'Langfuse datasets · experiments · LLM-as-judge',
  traces: 'OTEL → Langfuse',
  policy: 'OPA / Rego',
  safety: 'FastAPI guardrails',
  ci: 'GitHub Actions',
  explorer: 'Chroma Vector Explorer',
  ingestTab: 'Chroma Explorer',
  journey: {
    prometheus: ['Prometheus', 'Scrape + rule evaluation'],
    vector: ['Chroma RAG · Runbook retrieval', 'Chroma · semantic search'],
    logs: ['Query logs · Loki', 'Tool · query_logs'],
    metrics: ['Query metrics · Prometheus', 'Tool · query_metrics'],
    policy: ['OPA policy check', 'Rego · allow/deny destructive actions'],
  },
  policyConsole: 'Open OPA :8181',
  policyUrl: 'http://localhost:8181',
  logsQuery: 'Loki · {app="checkout-service"}',
  alertFiring: 'Prometheus Alert FIRING',
  vectorApiList: 'list_collections()',
  vectorApiQuery: 'collection.query()',
  ports: [
    ['3000', 'Langfuse'],
    ['9090', 'Prometheus'],
    ['3100', 'Loki'],
    ['8181', 'OPA'],
  ],
  phases: {
    ingestion: ['Alertmanager', 'Loki + Promtail', 'Prometheus', 'Grafana', 'ChromaDB'],
    orchestration: ['LangGraph', 'Gateway UI', 'MCP servers', 'Ollama'],
    evaluation: ['Langfuse'],
    guardrails: ['OPA / Rego', 'HITL gate', 'FastAPI'],
    action: ['PostgreSQL', 'Ticket API', 'GitHub Actions'],
  },
  explore: [
    { key: 'chroma', label: 'Chroma', url: '/static/tools/chroma.html', urlLabel: 'embedded · console', role: 'vector', hint: 'Browse runbook chunks in the in-console Chroma UI', hover: 'VECTOR DB — Chroma has no vendor GUI. Open this console and list the runbooks collection.' },
    { key: 'grafana', label: 'Loki in Grafana', url: 'http://localhost:3001/explore?orgId=1&left=%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bjob%3D%5C%22agentops%5C%22%7D%22%7D%5D%7D', urlLabel: 'localhost:3001 · Explore Loki', role: 'logs', hint: 'LOGS — Grafana Explore → datasource Loki. Query {job="agentops"}', hover: 'LOGS only. Grafana → Explore (compass) → datasource Loki (not Prometheus). Query {job="agentops"}. Time range Last 6h. Loki has no own GUI.' },
    { key: 'prometheus', label: 'Prometheus', url: 'http://localhost:9090/graph', urlLabel: 'localhost:9090', role: 'metrics', hint: 'METRICS — Graph UI, query service_error_rate', hover: 'METRICS only. Prometheus graph at :9090 — query service_error_rate. Not VictoriaMetrics :8428. Not logs.' },
    { key: 'grafana', label: 'Grafana', url: 'http://localhost:3001/d/design1-checkout-incident?orgId=1', role: 'dashboards', hint: 'admin / admin · folder AgentOps Design 1', hover: 'admin / admin. Left menu → Dashboards → AgentOps Design 1. Explore → Loki for logs, Prometheus for metrics.' },
    { key: 'langfuse', label: 'Langfuse', url: 'http://localhost:3000', role: 'llmops', hint: 'a@ex.com / 123456789 · Tracing · Playground · Prompts', hover: 'Design 1 LLM ops (Langfuse v3 — same surface as github.com/langfuse/langfuse). Login a@ex.com / 123456789. Tracing for spans/generations/events. Playground iterates prompts against Ollama. Prompts versions the classify/recommend templates.' },
    { key: 'langfuse', label: 'Langfuse Evaluation', url: 'http://localhost:3000', role: 'evals', hint: 'Datasets · experiments · LLM-as-judge', hover: 'Design 1 EVAL. Left nav Evaluation + Datasets. After Run Eval Suite: Datasets → ops-triage-golden. Evaluation → LLM-as-judge once an LLM connection to Ollama is set in Settings. Not MLflow, not Phoenix.' },
  ],
  tiles: [
    { id: 'link-grafana', key: 'grafana', label: 'Grafana' },
    { id: 'link-prometheus', key: 'prometheus', label: 'Prometheus' },
    { id: 'link-langfuse', key: 'langfuse', label: 'Langfuse' },
    { id: 'link-mlflow', key: 'langfuse', label: 'Langfuse eval' },
  ],
};
