/** Design 3 stack pack — OpenSearch k-NN + Mimir + Tempo + MLflow */
window.ARCH_DESIGN_PACKS = window.ARCH_DESIGN_PACKS || {};
window.ARCH_DESIGN_LOGOS = Object.assign(window.ARCH_DESIGN_LOGOS || {}, {
  opensearch: { label: 'OpenSearch', src: '/static/designs/d3/logos/opensearch.svg?v=1' },
  mimir: { label: 'Grafana Mimir', src: '/static/designs/d3/logos/mimir.svg?v=1' },
  tempo: { label: 'Grafana Tempo', src: '/static/designs/d3/logos/tempo.svg?v=1' },
});

window.ARCH_DESIGN_PACKS.d3 = {
  id: 'd3',
  n: 3,
  name: 'Design 3',
  tagline: 'OpenSearch unified data plane',
  stack: 'OpenSearch k-NN + Mimir + Tempo + MLflow',
  deploy: './deploy.sh up-d3',
  pick: 'One search plane. Grafana for metrics and traces.',
  vector: 'OpenSearch k-NN',
  vectorUrl: 'http://localhost:5602/app/data-explorer/discover',
  logs: 'OpenSearch + Fluent Bit',
  metrics: 'Prometheus + Mimir',
  dashboards: 'OpenSearch Dashboards + Grafana',
  llmops: 'MLflow',
  evals: 'MLflow tracing · experiments · LLM-as-judge',
  traces: 'MLflow Tracing',
  policy: 'OPA / Rego',
  safety: 'NeMo Guardrails (optional)',
  ci: 'GitLab CI',
  explorer: 'OpenSearch Vector Explorer',
  ingestTab: 'OpenSearch Explorer',
  journey: {
    prometheus: ['Prometheus + Mimir', 'Scrape → remote_write to Mimir'],
    vector: ['OpenSearch k-NN · Runbook retrieval', 'OpenSearch · semantic search'],
    logs: ['Query logs · OpenSearch', 'Tool · query_logs'],
    metrics: ['Query metrics · Mimir', 'Tool · query_metrics'],
    traces: ['Query traces · Tempo', 'OTEL · Grafana Explore · Tempo'],
    policy: ['OPA policy check', 'Rego · allow/deny destructive actions'],
  },
  policyConsole: 'Open OPA :8181',
  policyUrl: 'http://localhost:8181',
  logsQuery: 'OpenSearch · service:checkout-service',
  alertFiring: 'Mimir Alert FIRING',
  vectorApiList: 'knn index',
  vectorApiQuery: 'knn query',
  ports: [
    ['5602', 'OpenSearch Dashboards'],
    ['9201', 'OpenSearch'],
    ['9009', 'Mimir'],
    ['3200', 'Grafana Tempo'],
    ['5001', 'MLflow'],
    ['8181', 'OPA'],
  ],
  phases: {
    ingestion: ['Alertmanager', 'OpenSearch + Fluent Bit', 'Prometheus + Mimir', 'OSD + Grafana', 'OpenSearch k-NN'],
    orchestration: ['LangGraph', 'Gateway UI', 'MCP servers', 'Ollama'],
    evaluation: ['MLflow'],
    guardrails: ['OPA / Rego', 'HITL gate', 'NeMo (optional)'],
    action: ['PostgreSQL', 'Ticket API', 'GitLab CI'],
  },
  explore: [
    { key: 'opensearch', label: 'OpenSearch Dashboards', url: 'http://localhost:5602/app/data-explorer/discover', urlLabel: 'localhost:5602 · Discover', role: 'vector', hint: 'VECTOR — Discover index agentops-d3-runbooks', hover: 'VECTOR / RAG docs. OpenSearch Dashboards Discover. Index pattern agentops-d3-runbooks (k-NN runbooks). Switch to agentops-d3-logs for logs.' },
    { key: 'opensearch', label: 'OpenSearch logs', url: 'http://localhost:5602/app/data-explorer/discover', urlLabel: 'localhost:5602 · Discover', role: 'logs', hint: 'LOGS — Discover index agentops-d3-logs (not Grafana)', hover: 'LOGS live here. OpenSearch Dashboards :5602 → Discover → index agentops-d3-logs. Grafana Mimir/Tempo do NOT show logs.' },
    { key: 'opensearch', label: 'OpenSearch API', url: 'http://localhost:9201', role: 'logs-api', hint: 'Raw cluster JSON — use Dashboards', sidebar: false },
    { key: 'mimir', label: 'Mimir in Grafana', url: 'http://localhost:3001/explore?orgId=1&left=%7B%22datasource%22:%22mimir%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22service_error_rate%22%7D%5D%7D', role: 'metrics', hint: 'METRICS — Explore → datasource Mimir → service_error_rate', hover: 'METRICS only. Grafana admin/admin → Explore (compass) → datasource Mimir (not VictoriaMetrics). Query service_error_rate. Mimir has no vendor GUI. This is NOT logs.' },
    { key: 'grafana', label: 'Grafana', url: 'http://localhost:3001/d/design3-mimir-tempo?orgId=1', role: 'dashboards', hint: 'admin / admin · folder AgentOps Design 3', hover: 'admin / admin. Dashboards → AgentOps Design 3. Mimir panels = metrics. Tempo panel = traces. Logs are OpenSearch Dashboards, not this page.' },
    { key: 'mlflow', label: 'MLflow', url: 'http://localhost:5001', role: 'llmops', hint: 'Traces + experiments — Design 3 LLM ops', hover: 'Design 3 LLM TRACES. MLflow :5001 → Experiments → ops-triage-d3. Open a run to see traces and llm-as-judge spans. Not Langfuse, not Phoenix.' },
    { key: 'tempo', label: 'Tempo in Grafana', url: 'http://localhost:3001/explore?orgId=1&left=%7B%22datasource%22:%22tempo%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22queryType%22:%22traceqlSearch%22%7D%5D%7D', role: 'traces', hint: 'Infra traces — Explore → Tempo', hover: 'INFRA TRACES only (OTEL). Grafana Explore → Tempo. LLM eval lives in MLflow, not here. Not logs, not metrics.' },
    { key: 'mlflow', label: 'MLflow eval', url: 'http://localhost:5001', role: 'evals', hint: 'Evaluate · LLM-as-judge artifacts', hover: 'Design 3 EVAL. After Run Eval Suite: MLflow experiment ops-triage-d3 → run eval-* → metrics + artifacts eval_report.json and llm_judge.md. This is the whole eval story for D3.' },
  ],
  tiles: [
    { id: 'link-grafana', key: 'opensearch', label: 'OpenSearch Dashboards' },
    { id: 'link-prometheus', key: 'mimir', label: 'Mimir' },
    { id: 'link-langfuse', key: 'mlflow', label: 'MLflow' },
    { id: 'link-mlflow', key: 'mlflow', label: 'MLflow eval' },
  ],
};
