/** Design 2 stack pack — Weaviate + Elasticsearch + VictoriaMetrics + Phoenix */
window.ARCH_DESIGN_PACKS = window.ARCH_DESIGN_PACKS || {};
window.ARCH_DESIGN_LOGOS = Object.assign(window.ARCH_DESIGN_LOGOS || {}, {
  kibana: { label: 'Kibana', src: '/static/designs/d2/logos/kibana.svg?v=1' },
  elasticsearch: { label: 'Elasticsearch', src: '/static/designs/d2/logos/elasticsearch.svg?v=1' },
  victoriametrics: { label: 'VictoriaMetrics', src: '/static/designs/d2/logos/victoriametrics.svg?v=1' },
  phoenix: { label: 'Arize Phoenix', src: '/static/designs/d2/logos/phoenix.svg?v=1' },
  weaviate: { label: 'Weaviate', src: '/static/designs/d2/logos/weaviate.svg?v=1' },
});

window.ARCH_DESIGN_PACKS.d2 = {
  id: 'd2',
  n: 2,
  name: 'Design 2',
  tagline: 'ELK shop + Weaviate + Phoenix',
  stack: 'Weaviate + Elasticsearch + VictoriaMetrics + Phoenix',
  deploy: './deploy.sh up',
  pick: 'You already live in Elastic. Add Weaviate + Phoenix.',
  vector: 'Weaviate',
  vectorUrl: '/static/tools/weaviate.html',
  logs: 'Elasticsearch + Filebeat',
  metrics: 'VictoriaMetrics',
  dashboards: 'Kibana + Grafana',
  llmops: 'Arize Phoenix',
  evals: 'Phoenix traces · experiments · LLM-as-judge',
  traces: 'OTEL → Phoenix',
  policy: 'OpenFGA',
  safety: 'Presidio PII',
  ci: 'GitHub Actions',
  explorer: 'Weaviate Vector Explorer',
  ingestTab: 'Weaviate Explorer',
  journey: {
    prometheus: ['VictoriaMetrics', 'Scrape + rule evaluation'],
    vector: ['Weaviate RAG · Runbook retrieval', 'Weaviate · semantic search'],
    logs: ['Query logs · Elasticsearch', 'Tool · query_logs'],
    metrics: ['Query metrics · VictoriaMetrics', 'Tool · query_metrics'],
    policy: ['OpenFGA authorization check', 'Tuple · allow/deny destructive actions'],
  },
  policyConsole: 'Open OpenFGA :8085',
  policyUrl: 'http://localhost:8085',
  logsQuery: 'Elasticsearch · service:checkout-service',
  alertFiring: 'VictoriaMetrics Alert FIRING',
  vectorApiList: 'Weaviate class',
  vectorApiQuery: 'nearText()',
  ports: [
    ['8088', 'Weaviate'],
    ['9200', 'Elasticsearch'],
    ['8428', 'VictoriaMetrics'],
    ['6006', 'Arize Phoenix'],
    ['5601', 'Kibana'],
    ['8085', 'OpenFGA'],
    ['8084', 'Presidio'],
  ],
  phases: {
    ingestion: ['Grafana Alerting', 'Elasticsearch + Filebeat', 'VictoriaMetrics', 'Kibana', 'Weaviate'],
    orchestration: ['LangGraph', 'Gateway UI', 'MCP servers', 'Ollama'],
    evaluation: ['Phoenix'],
    guardrails: ['OpenFGA', 'HITL gate', 'Presidio'],
    action: ['PostgreSQL', 'Ticket API', 'GitHub Actions'],
  },
  explore: [
    { key: 'weaviate', label: 'Weaviate', url: '/static/tools/weaviate.html', urlLabel: 'localhost:8088', role: 'vector', hint: 'Browse Runbook objects + GraphQL', hover: 'VECTOR DB — Weaviate console. Class Runbook. Live RAG for this laptop.' },
    { key: 'kibana', label: 'Kibana', url: 'http://localhost:5601', role: 'logs', hint: 'LOGS — Discover, not :9200 JSON', hover: 'LOGS. Kibana :5601 → Discover. Index agentops-logs. Elasticsearch :9200 is raw JSON — do not demo that.' },
    { key: 'elasticsearch', label: 'Elasticsearch API', url: 'http://localhost:9200', role: 'logs-api', hint: 'Raw cluster JSON — use Kibana', sidebar: false },
    { key: 'victoriametrics', label: 'VictoriaMetrics', url: 'http://localhost:8428/vmui', role: 'metrics', hint: 'METRICS — vmui, query service_error_rate', hover: 'METRICS only. vmui Query: service_error_rate. Not Prometheus :9090. Not logs.' },
    { key: 'grafana', label: 'Grafana', url: 'http://localhost:3001/d/design2-checkout-incident?orgId=1', role: 'dashboards', hint: 'admin / admin · folder AgentOps Design 2', hover: 'admin / admin. Dashboards → AgentOps Design 2. Datasource VictoriaMetrics for metrics. Logs belong in Kibana, not here.' },
    { key: 'phoenix', label: 'Phoenix', url: 'http://localhost:6006', role: 'llmops', hint: 'Traces — Design 2 LLM ops', hover: 'Design 2 LLM TRACES. Phoenix :6006 → Traces. Do not open Langfuse for this design.' },
    { key: 'phoenix', label: 'Phoenix Experiments', url: 'http://localhost:6006', role: 'evals', hint: 'Datasets · evaluations · LLM-as-judge', hover: 'Design 2 EVAL. After Run Eval Suite: Phoenix Datasets / Experiments and Evaluations → llm_judge_groundedness. Not Langfuse, not MLflow.' },
  ],
  tiles: [
    { id: 'link-grafana', key: 'kibana', label: 'Kibana / Grafana' },
    { id: 'link-prometheus', key: 'victoriametrics', label: 'VictoriaMetrics' },
    { id: 'link-langfuse', key: 'phoenix', label: 'Phoenix' },
    { id: 'link-mlflow', key: 'phoenix', label: 'Phoenix eval' },
  ],
};
